


all:
	cd SampleDriveControl; make
	cd SampleGetSensor; make
	cd SampleLRS; make
	cd SampleSocketCommunication; make

clean:
	cd SampleDriveControl; make clean
	cd SampleGetSensor; make clean
	cd SampleLRS; make clean
	cd SampleSocketCommunication; make clean



